#ifndef PUREMVC_MACROCOMMANDTESTSUB2COMMAND_H
#define PUREMVC_MACROCOMMANDTESTSUB2COMMAND_H

#include "interfaces/SimpleCommand.h"

SimpleCommand *NewMacroCommandTestSub2Command();

#endif //PUREMVC_MACROCOMMANDTESTSUB2COMMAND_H
